VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "DataValue"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public nodeName As String
Public SampleTime As String
Public SP_Value As String
Public SP_Raw As String
Public SP_Appendix As String
Public OP_Value As String
Public OP_Raw As String
Public OP_Appendix As String
Public PV_Value As String
Public PV_Raw As String
Public PV_Appendix As String




